---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mediocrethemes

<!-- badges: start -->
<!-- badges: end -->

This package provides not particularly nice and, hopefully, not particularly hugly ggplot themes.

## Installation

You can install the development version of `mediocrethemes` from [GitHub](https://github.com/) with:

```{r}
# install.packages("devtools")
# devtools::install_github("vincentbagilet/mediocrethemes")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
# library(mediocrethemes)
## basic example code
```

There are several base colors for in this theme (gray, )

```{r}
# library(ggplot2)
# 
# ggplot(aes(data = ggplot2::mpg, x = cty, y = displ)) +
#     geom_point() +
#     theme_mediocre() +
#     labs(title = "A very nice title", subtitle = "A desapointing subtitle")
# 
# ggplot(aes(ata = ggplot2::mpg, x = cty, y = displ, fill = manufacturer)) +
#     geom_col() +
#     theme_mediocre() +
#     labs(title = "A very nice title", subtitle = "A desapointing subtitle")
```


